on: push
jobs:
    first-job:
        runs-on: windows-latest
        steps:
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v3
            - run: npm install 
            - run: npm run build
            - run: npm test
            
